services:
  db:
    container_name: postgres-db
    environment:
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: Postgres2021
      POSTGRES_DB: transactionaldb
    image: postgres
    ports:
      - "5432:5432"
    restart: always
  transactionalapi:
    build: "."
    container_name: transactionalapi
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/transactionaldb
      SPRING_DATASOURCE_USERNAME: compose-postgres
      SPRING_DATASOURCE_PASSWORD: Postgres2021
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: on-failure
version: "3.3"